micronaut.application.name: in-memory-db
aol:
  dir: ${AOL_DIR:/tmp/in-memory-db}
  filename: ${AOL_FILE_NAME:append-only-log}
  flushInterval: ${AOL_LOG_FLUSH_INTERVAL:2s}
  bufferSize: ${AOL_BUFFER_SIZE:694460}
  initialMapCapacity: ${AOL_INITIAL_MAP_CAPACITY:1620000}
